# Contenu généré pour démarrer — à faire relire par quelqu'un qui maîtrise le
# format TCF Canada avant mise en production, pour garantir la validité
# pédagogique.
from database import db_cursor

PACKS = [
    {
        "name": "5 jours",
        "description": "Pour un test rapide de votre niveau : accès à tout le contenu (tests illimités) pendant 5 jours, avec 5 corrections IA de vos productions écrites/orales.",
        "price_mad": 99.0,
        "original_price_mad": 149.0,
        "is_popular": 0,
        "duration_days": 5,
        "ai_correction_credits": 5,
    },
    {
        "name": "30 jours",
        "description": "La formule la plus choisie : accès complet pendant 30 jours, avec 15 corrections IA de vos productions écrites/orales.",
        "price_mad": 249.0,
        "original_price_mad": 349.0,
        "is_popular": 1,
        "duration_days": 30,
        "ai_correction_credits": 15,
    },
    {
        "name": "60 jours",
        "description": "Pour une préparation complète dans la durée : accès complet pendant 60 jours, avec 30 corrections IA de vos productions écrites/orales.",
        "price_mad": 449.0,
        "original_price_mad": 599.0,
        "is_popular": 0,
        "duration_days": 60,
        "ai_correction_credits": 30,
    },
]

TCF_QUESTIONS = [
    # --- Compréhension écrite ---
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "D'après l'annonce, à quelle heure ouvre le magasin le dimanche ?",
        "passage_or_audio_desc": "Annonce : « Le magasin est ouvert du lundi au samedi de 9h à 19h. Le dimanche, ouverture à 10h et fermeture à 13h. »",
        "option_a": "9h",
        "option_b": "10h",
        "option_c": "13h",
        "option_d": "19h",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Quel est le but principal de ce message ?",
        "passage_or_audio_desc": "Message : « Suite à votre appel de ce matin, je vous confirme que votre dossier de demande de résidence a bien été reçu. Un conseiller vous contactera sous 48h. »",
        "option_a": "Refuser une demande",
        "option_b": "Demander un paiement",
        "option_c": "Confirmer la réception d'un dossier",
        "option_d": "Annuler un rendez-vous",
        "correct_option": "c",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Quelle est l'idée principale défendue par l'auteur du texte ?",
        "passage_or_audio_desc": "Texte : « Si l'immigration économique soutient la croissance démographique du Canada, elle exige aussi un accompagnement renforcé des nouveaux arrivants sur le marché du travail, sous peine de creuser les inégalités régionales. »",
        "option_a": "L'immigration n'a aucun effet sur l'économie",
        "option_b": "L'immigration est bénéfique mais nécessite un meilleur accompagnement",
        "option_c": "Il faut arrêter l'immigration économique",
        "option_d": "Les inégalités régionales n'existent pas",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "Que doit faire le destinataire avant vendredi ?",
        "passage_or_audio_desc": "Courriel : « Merci de nous renvoyer le formulaire signé avant vendredi afin que nous puissions traiter votre demande. »",
        "option_a": "Payer une facture",
        "option_b": "Renvoyer un formulaire signé",
        "option_c": "Appeler le bureau",
        "option_d": "Annuler sa demande",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Quel ton l'auteur adopte-t-il dans cet extrait ?",
        "passage_or_audio_desc": "Extrait : « Loin des discours convenus sur l'intégration, force est de constater que les dispositifs actuels peinent, malgré leur multiplication, à produire des résultats tangibles. »",
        "option_a": "Enthousiaste",
        "option_b": "Neutre et factuel",
        "option_c": "Critique",
        "option_d": "Humoristique",
        "correct_option": "c",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Combien de documents sont demandés dans cette liste ?",
        "passage_or_audio_desc": "Liste de documents requis : passeport valide, certificat de naissance, relevé de notes, lettre de motivation.",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_option": "c",
    },
    # --- Compréhension orale (transcriptions fournies comme substitut à l'audio) ---
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Où se trouve la personne qui parle ?",
        "passage_or_audio_desc": "🔊 Transcription : « Bonjour à tous les passagers, notre train à destination de Montréal partira du quai numéro 3 dans dix minutes. »",
        "option_a": "Dans un aéroport",
        "option_b": "Dans une gare",
        "option_c": "Dans un bus",
        "option_d": "Dans un magasin",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Que propose la personne à son collègue ?",
        "passage_or_audio_desc": "🔊 Transcription : « Écoute, si tu veux, on peut se répartir le dossier : je m'occupe des entretiens, et toi tu gères la paperasse administrative. »",
        "option_a": "De changer de projet",
        "option_b": "De se partager les tâches",
        "option_c": "D'annuler le dossier",
        "option_d": "De prendre des vacances",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quelle est l'opinion de la personne interrogée sur le nouveau programme ?",
        "passage_or_audio_desc": "🔊 Transcription : « Honnêtement, sur le papier c'est séduisant, mais dans les faits, les délais de traitement restent bien trop longs pour que ça change vraiment la donne. »",
        "option_a": "Très positive",
        "option_b": "Neutre, sans avis",
        "option_c": "Mitigée, sceptique",
        "option_d": "Totalement négative",
        "correct_option": "c",
    },
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Quel jour aura lieu le rendez-vous ?",
        "passage_or_audio_desc": "🔊 Transcription : « Votre rendez-vous initialement prévu jeudi a été déplacé à mardi prochain, même heure. »",
        "option_a": "Jeudi",
        "option_b": "Vendredi",
        "option_c": "Mardi",
        "option_d": "Lundi",
        "correct_option": "c",
    },
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Quel est le principal argument avancé par l'intervenant ?",
        "passage_or_audio_desc": "🔊 Transcription : « Ce qu'on observe, c'est que la réussite de l'intégration tient moins à la maîtrise linguistique initiale qu'à la densité du réseau professionnel que la personne parvient à se constituer dès les premiers mois. »",
        "option_a": "La langue est le seul facteur de réussite",
        "option_b": "Le réseau professionnel est déterminant, plus que le niveau de langue initial",
        "option_c": "L'intégration ne dépend d'aucun facteur identifiable",
        "option_d": "Les premiers mois n'ont pas d'importance",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Que doit apporter la personne pour son rendez-vous ?",
        "passage_or_audio_desc": "🔊 Transcription : « N'oubliez pas d'apporter une pièce d'identité valide ainsi que la confirmation de rendez-vous imprimée. »",
        "option_a": "Seulement une pièce d'identité",
        "option_b": "Une pièce d'identité et la confirmation imprimée",
        "option_c": "Un chèque",
        "option_d": "Rien de particulier",
        "correct_option": "b",
    },
]

# --- Contenu additionnel (25 compréhension écrite + 25 compréhension orale) ---
# Contenu 100% original, écrit pour cette plateforme dans l'esprit du format
# TCF Canada (mini-textes variés : annonces, courriels, articles, extraits
# d'opinion). Voir avertissement en tête de fichier.
TCF_QUESTIONS_EXTRA = [
    # ===== Compréhension écrite — niveau A2 (6) =====
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "Que comprend le loyer, d'après l'annonce ?",
        "passage_or_audio_desc": "Annonce : « Recherche colocataire, appartement 2 pièces, disponible dès le 1er septembre, loyer 650$/mois charges comprises. »",
        "option_a": "Rien de particulier",
        "option_b": "Les charges",
        "option_c": "Le wifi uniquement",
        "option_d": "Le stationnement",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "Où la personne doit-elle récupérer sa carte ?",
        "passage_or_audio_desc": "Courriel : « Bonjour, je vous informe que votre carte de bibliothèque est prête. Vous pouvez venir la récupérer au comptoir principal entre 9h et 17h. »",
        "option_a": "Par courrier",
        "option_b": "Au comptoir principal",
        "option_c": "En ligne",
        "option_d": "Au bureau de poste",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "À quelle fréquence ont lieu les cours ?",
        "passage_or_audio_desc": "Affiche : « Cours de français gratuits pour nouveaux arrivants, tous les mardis et jeudis de 18h à 20h, salle communautaire. »",
        "option_a": "Une fois par semaine",
        "option_b": "Deux fois par semaine",
        "option_c": "Tous les jours",
        "option_d": "Une fois par mois",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "Que doit apporter la personne pour récupérer son colis ?",
        "passage_or_audio_desc": "SMS : « Ton colis est arrivé au bureau de poste, viens le chercher avec une pièce d'identité avant vendredi. »",
        "option_a": "De l'argent",
        "option_b": "Une pièce d'identité",
        "option_c": "Un formulaire signé",
        "option_d": "Rien",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "Qui peut se garer ici le week-end ?",
        "passage_or_audio_desc": "Panneau : « Stationnement réservé aux résidents du lundi au vendredi de 8h à 18h. »",
        "option_a": "Personne",
        "option_b": "Seulement les résidents",
        "option_c": "Tout le monde",
        "option_d": "Seulement les livreurs",
        "correct_option": "c",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "A2",
        "question_text": "Quand le magasin est-il fermé ?",
        "passage_or_audio_desc": "Avis : « Le magasin ferme exceptionnellement le 25 décembre et le 1er janvier. »",
        "option_a": "Tous les dimanches",
        "option_b": "Le 25 décembre et le 1er janvier",
        "option_c": "Pendant tout le mois de décembre",
        "option_d": "Le magasin ne ferme jamais",
        "correct_option": "b",
    },
    # ===== Compréhension écrite — niveau B1 (7) =====
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Quel est l'objet de ce message ?",
        "passage_or_audio_desc": "Courriel : « Nous accusons réception de votre candidature pour le poste d'assistant administratif. Un membre de notre équipe vous contactera dans les deux semaines pour organiser un entretien. »",
        "option_a": "Refuser la candidature",
        "option_b": "Confirmer la réception d'une candidature",
        "option_c": "Annoncer une embauche",
        "option_d": "Demander des documents supplémentaires",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Que nous apprend ce texte ?",
        "passage_or_audio_desc": "Article : « Le nombre de nouveaux arrivants inscrits aux cours de francisation a doublé cette année dans la région, selon les chiffres municipaux. »",
        "option_a": "Moins de gens apprennent le français",
        "option_b": "Le nombre d'inscriptions a augmenté",
        "option_c": "Les cours ont été annulés",
        "option_d": "La région a perdu des habitants",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Que doit faire le destinataire de cette lettre ?",
        "passage_or_audio_desc": "Lettre administrative : « Votre dossier est actuellement en traitement. Aucune action n'est requise de votre part pour le moment ; nous vous recontacterons dès qu'une décision sera prise. »",
        "option_a": "Envoyer un document urgent",
        "option_b": "Attendre sans rien faire de particulier",
        "option_c": "Payer des frais",
        "option_d": "Prendre rendez-vous immédiatement",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Pourquoi la ligne de bus change-t-elle d'itinéraire ?",
        "passage_or_audio_desc": "Avis municipal : « En raison de travaux, la ligne de bus 12 sera déviée à partir de lundi. Merci d'utiliser l'arrêt temporaire situé rue des Érables. »",
        "option_a": "Un accident",
        "option_b": "Des travaux",
        "option_c": "Une grève",
        "option_d": "Une fête locale",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Quel document n'est PAS mentionné dans ce texte ?",
        "passage_or_audio_desc": "Guide pratique : « Pour ouvrir un compte bancaire, il est généralement demandé une pièce d'identité, une preuve d'adresse et parfois un numéro d'assurance sociale. »",
        "option_a": "Pièce d'identité",
        "option_b": "Preuve d'adresse",
        "option_c": "Numéro d'assurance sociale",
        "option_d": "Relevé de notes scolaire",
        "correct_option": "d",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Qu'est-ce qui a changé concernant la réunion ?",
        "passage_or_audio_desc": "Courriel d'école : « Merci de noter que la réunion de parents initialement prévue le 10 a été reportée au 17 du même mois, à la même heure. »",
        "option_a": "L'heure",
        "option_b": "Le lieu",
        "option_c": "La date",
        "option_d": "Rien n'a changé",
        "correct_option": "c",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B1",
        "question_text": "Quelle compétence est exigée dans cette offre d'emploi ?",
        "passage_or_audio_desc": "Annonce d'emploi : « Nous recherchons un(e) candidat(e) bilingue français-anglais, avec au moins un an d'expérience en service à la clientèle, pour un poste à temps plein. »",
        "option_a": "Expérience en comptabilité",
        "option_b": "Bilinguisme français-anglais",
        "option_c": "Diplôme universitaire",
        "option_d": "Permis de conduire",
        "correct_option": "b",
    },
    # ===== Compréhension écrite — niveau B2 (6) =====
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Quel est le sujet du débat présenté dans cet extrait ?",
        "passage_or_audio_desc": "Extrait d'opinion : « Certains estiment que l'apprentissage accéléré d'une langue nuit à sa maîtrise durable, alors que d'autres y voient au contraire un formidable accélérateur d'intégration professionnelle. »",
        "option_a": "Le coût des cours de langue",
        "option_b": "L'efficacité de l'apprentissage rapide d'une langue",
        "option_c": "La difficulté de trouver un emploi",
        "option_d": "Les vacances scolaires",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Quel constat fait cette étude ?",
        "passage_or_audio_desc": "Article : « La pénurie de logements abordables continue de peser sur les nouveaux arrivants, qui consacrent en moyenne une part croissante de leur revenu au loyer, selon une étude récente. »",
        "option_a": "Les loyers ont baissé",
        "option_b": "Les nouveaux arrivants dépensent davantage pour se loger",
        "option_c": "Il y a trop de logements vacants",
        "option_d": "Le revenu moyen a fortement augmenté",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Selon l'auteur, la maîtrise du français au travail dépend aussi de quoi ?",
        "passage_or_audio_desc": "Éditorial : « Loin de se limiter à une question de vocabulaire, la maîtrise du français dans un contexte professionnel implique aussi de comprendre les codes culturels propres au milieu de travail. »",
        "option_a": "Uniquement de la grammaire",
        "option_b": "De la rapidité de parole",
        "option_c": "Des codes culturels du milieu professionnel",
        "option_d": "Du salaire proposé",
        "correct_option": "c",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Que dit ce texte sur les délais de traitement ?",
        "passage_or_audio_desc": "Extrait de rapport : « Bien que les délais de traitement des demandes se soient globalement raccourcis, des disparités importantes subsistent selon les catégories de programmes. »",
        "option_a": "Ils ont augmenté partout",
        "option_b": "Ils sont identiques pour tous les programmes",
        "option_c": "Ils ont diminué mais restent inégaux selon les programmes",
        "option_d": "Ils n'existent plus",
        "correct_option": "c",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Quel atout la personne met-elle en avant dans cet extrait ?",
        "passage_or_audio_desc": "Lettre de motivation : « Mon parcours atypique, entre enseignement et gestion de projet, m'a permis de développer une capacité d'adaptation que je considère comme un atout pour ce poste. »",
        "option_a": "Son ancienneté",
        "option_b": "Sa capacité d'adaptation",
        "option_c": "Son réseau professionnel",
        "option_d": "Son niveau d'anglais",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "B2",
        "question_text": "Quelle est l'idée principale de cet extrait ?",
        "passage_or_audio_desc": "Analyse : « Si l'accès à un logement stable facilite indéniablement l'intégration, il ne suffit pas à lui seul à garantir une insertion professionnelle réussie. »",
        "option_a": "Le logement est sans importance",
        "option_b": "Le logement aide, mais ne garantit pas l'emploi",
        "option_c": "Le logement garantit toujours un emploi",
        "option_d": "L'emploi n'a aucun lien avec le logement",
        "correct_option": "b",
    },
    # ===== Compréhension écrite — niveau C1 (6) =====
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Que reprochent les candidats, malgré les efforts mentionnés ?",
        "passage_or_audio_desc": "Extrait : « Nonobstant les efforts déployés pour fluidifier les démarches administratives, nombre de candidats déplorent encore une opacité persistante quant aux critères réellement déterminants dans l'évaluation de leur dossier. »",
        "option_a": "Le coût des démarches",
        "option_b": "Le manque de clarté sur les critères d'évaluation",
        "option_c": "La lenteur des transports",
        "option_d": "L'absence de formulaires en ligne",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Quel est le ton de cet extrait ?",
        "passage_or_audio_desc": "Chronique : « À rebours du discours ambiant vantant les mérites de la mobilité internationale, certains sociologues pointent le coût psychologique souvent sous-estimé du déracinement. »",
        "option_a": "Enthousiaste et sans nuance",
        "option_b": "Critique et nuancé",
        "option_c": "Purement descriptif",
        "option_d": "Ironique et léger",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Quelle position l'auteur critique-t-il dans cet extrait ?",
        "passage_or_audio_desc": "Texte argumentatif : « Prétendre que la seule maîtrise linguistique suffit à garantir une intégration réussie relève d'une vision par trop réductrice des dynamiques sociales à l'œuvre. »",
        "option_a": "L'idée que la langue seule garantit l'intégration",
        "option_b": "L'idée que la langue est inutile",
        "option_c": "L'idée que l'intégration est impossible",
        "option_d": "L'idée que les dynamiques sociales n'existent pas",
        "correct_option": "a",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Quelle nuance l'auteur apporte-t-il dans cet extrait ?",
        "passage_or_audio_desc": "Éditorial : « Si l'on se réjouit à juste titre de l'assouplissement de certaines conditions d'admissibilité, il conviendrait de ne pas sous-estimer les effets de bord d'une telle libéralisation sur des dispositifs déjà sous tension. »",
        "option_a": "Il n'y a aucun risque à cet assouplissement",
        "option_b": "L'assouplissement pourrait avoir des effets secondaires sur des dispositifs déjà fragiles",
        "option_c": "Il faut annuler l'assouplissement immédiatement",
        "option_d": "Les dispositifs ne sont jamais sous tension",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Que suggère cette phrase sur les démarches administratives ?",
        "passage_or_audio_desc": "Extrait au style soutenu : « Ce n'est qu'au prix d'une patience à toute épreuve que l'on parvient, bribe après bribe, à reconstituer les pièces d'un dossier administratif digne de ce nom. »",
        "option_a": "Elles sont rapides et simples",
        "option_b": "Elles nécessitent beaucoup de patience et de rigueur",
        "option_c": "Elles sont inutiles",
        "option_d": "Elles se font en une seule étape",
        "correct_option": "b",
    },
    {
        "section": "comprehension_ecrite",
        "niveau": "C1",
        "question_text": "Selon l'auteur, que reflète avant tout un score élevé au TCF Canada ?",
        "passage_or_audio_desc": "Extrait : « Loin d'être un simple sésame linguistique, un score élevé au TCF Canada atteste avant tout d'une capacité à mobiliser la langue dans des situations de communication variées et exigeantes. »",
        "option_a": "Une simple formalité administrative",
        "option_b": "Une capacité à utiliser la langue dans des situations variées et exigeantes",
        "option_c": "Un niveau de vocabulaire uniquement",
        "option_d": "Un certificat sans valeur réelle",
        "correct_option": "b",
    },
    # ===== Compréhension orale — niveau A2 (6) =====
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Où entend-on cette annonce ?",
        "passage_or_audio_desc": "🔊 Transcription : « Le prochain arrêt est Place-des-Arts. Merci de vérifier vos effets personnels avant de descendre. »",
        "option_a": "Dans un avion",
        "option_b": "Dans le métro ou le bus",
        "option_c": "Dans un magasin",
        "option_d": "À la banque",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Que demande la personne ?",
        "passage_or_audio_desc": "🔊 Transcription : « Bonjour, j'aimerais prendre rendez-vous pour une coupe de cheveux jeudi après-midi, si possible. »",
        "option_a": "Un remboursement",
        "option_b": "Un rendez-vous chez le coiffeur",
        "option_c": "Une livraison",
        "option_d": "Un renseignement sur les prix",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Que doivent faire les clients ?",
        "passage_or_audio_desc": "🔊 Transcription : « Attention, le magasin fermera dans quinze minutes. Merci de vous diriger vers les caisses. »",
        "option_a": "Continuer à magasiner",
        "option_b": "Se diriger vers les caisses",
        "option_c": "Sortir immédiatement sans payer",
        "option_d": "Attendre la réouverture",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Que demande la personne à son ami ?",
        "passage_or_audio_desc": "🔊 Transcription : « Peux-tu m'aider à porter ces sacs jusqu'à la voiture, s'il te plaît ? »",
        "option_a": "De l'aide pour porter des sacs",
        "option_b": "De l'argent",
        "option_c": "Un conseil",
        "option_d": "Une adresse",
        "correct_option": "a",
    },
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Quel jour est le rendez-vous chez le médecin ?",
        "passage_or_audio_desc": "🔊 Transcription : « Votre rendez-vous chez le médecin est confirmé pour mercredi à 14h30. »",
        "option_a": "Lundi",
        "option_b": "Mardi",
        "option_c": "Mercredi",
        "option_d": "Jeudi",
        "correct_option": "c",
    },
    {
        "section": "comprehension_orale",
        "niveau": "A2",
        "question_text": "Que conseille la personne ?",
        "passage_or_audio_desc": "🔊 Transcription : « Il pleut beaucoup ce matin, n'oublie pas ton parapluie avant de sortir. »",
        "option_a": "De prendre un parapluie",
        "option_b": "De rester à la maison",
        "option_c": "De prendre un taxi",
        "option_d": "D'annuler la sortie",
        "correct_option": "a",
    },
    # ===== Compréhension orale — niveau B1 (7) =====
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Pourquoi la personne hésite-t-elle à accepter le poste ?",
        "passage_or_audio_desc": "🔊 Transcription : « On m'a proposé un poste à temps partiel, mais j'hésite parce que le salaire est un peu bas pour mes besoins actuels. »",
        "option_a": "Le poste est trop loin",
        "option_b": "Le salaire lui semble insuffisant",
        "option_c": "Les horaires sont trop longs",
        "option_d": "Elle n'aime pas le poste",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Quelle difficulté rencontre la personne depuis son déménagement ?",
        "passage_or_audio_desc": "🔊 Transcription : « Depuis que j'ai déménagé, j'ai plus de mal à me concentrer sur mes cours du soir, il y a beaucoup de bruit dans le quartier. »",
        "option_a": "Le manque de cours disponibles",
        "option_b": "Le bruit qui nuit à sa concentration",
        "option_c": "Le coût des cours",
        "option_d": "La distance avec l'école",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Comment s'est terminé l'entretien ?",
        "passage_or_audio_desc": "🔊 Transcription : « Franchement, j'étais stressé avant l'entretien, mais finalement tout s'est bien passé et on m'a rappelé le lendemain. »",
        "option_a": "Mal, la personne n'a pas été rappelée",
        "option_b": "Bien, la personne a été recontactée",
        "option_c": "L'entretien a été annulé",
        "option_d": "La personne ne sait pas encore",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Pourquoi la décision est-elle reportée ?",
        "passage_or_audio_desc": "🔊 Transcription : « Le comité a décidé de reporter la décision à la semaine prochaine, le temps d'examiner tous les dossiers reçus. »",
        "option_a": "Il manque des dossiers",
        "option_b": "Pour examiner tous les dossiers reçus",
        "option_c": "Le comité est en vacances",
        "option_d": "La décision a déjà été prise",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Qu'est-ce que la personne a finalement trouvé, contrairement à ce qu'elle pensait ?",
        "passage_or_audio_desc": "🔊 Transcription : « Je pensais que la démarche serait compliquée, mais en fait le formulaire en ligne était plutôt simple à remplir. »",
        "option_a": "Le formulaire était très compliqué",
        "option_b": "Le formulaire était simple à remplir",
        "option_c": "Il n'y avait pas de formulaire",
        "option_d": "Le formulaire a été refusé",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Que souhaite organiser la personne ?",
        "passage_or_audio_desc": "🔊 Transcription : « Si le budget le permet, on aimerait organiser une petite fête pour l'arrivée des nouveaux employés. »",
        "option_a": "Une réunion urgente",
        "option_b": "Une fête pour accueillir de nouveaux employés",
        "option_c": "Un voyage d'affaires",
        "option_d": "Une formation obligatoire",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B1",
        "question_text": "Comment la personne a-t-elle eu les informations de la réunion ?",
        "passage_or_audio_desc": "🔊 Transcription : « Je n'ai pas pu venir à la réunion, mais j'ai lu le compte-rendu envoyé par courriel ce matin. »",
        "option_a": "Elle y a assisté",
        "option_b": "Par un compte-rendu envoyé par courriel",
        "option_c": "Par téléphone",
        "option_d": "Elle ne les a pas eues",
        "correct_option": "b",
    },
    # ===== Compréhension orale — niveau B2 (6) =====
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quel constat fait la personne ?",
        "passage_or_audio_desc": "🔊 Transcription : « Ce qui me frappe, c'est que malgré toutes les ressources disponibles en ligne, beaucoup de gens ne savent toujours pas par où commencer leurs démarches. »",
        "option_a": "Les ressources en ligne sont inutiles",
        "option_b": "Malgré les ressources, beaucoup ne savent pas comment commencer",
        "option_c": "Tout le monde maîtrise parfaitement les démarches",
        "option_d": "Il n'existe aucune ressource en ligne",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quelle nuance apporte la personne sur le marché du travail ?",
        "passage_or_audio_desc": "🔊 Transcription : « On a beau dire que le marché du travail se porte bien, dans certains secteurs, trouver un poste correspondant à ses qualifications reste un vrai parcours du combattant. »",
        "option_a": "Le marché du travail est excellent partout",
        "option_b": "Trouver un poste adapté reste difficile dans certains secteurs",
        "option_c": "Il n'y a aucune difficulté à trouver un emploi",
        "option_d": "Les qualifications ne comptent pas",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quelle opinion exprime la personne sur l'aide reçue ?",
        "passage_or_audio_desc": "🔊 Transcription : « Honnêtement, je trouve que le suivi proposé après l'installation est plus utile que l'aide reçue avant l'arrivée elle-même. »",
        "option_a": "L'aide avant l'arrivée est plus utile",
        "option_b": "Le suivi après l'installation est plus utile",
        "option_c": "Aucune aide n'est utile",
        "option_d": "Les deux aides sont inutiles",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quelle difficulté est mentionnée dans cet extrait ?",
        "passage_or_audio_desc": "🔊 Transcription : « Ce qui complique les choses, c'est que chaque province a ses propres critères, ce qui peut vite devenir déroutant pour les nouveaux arrivants. »",
        "option_a": "Les critères sont identiques partout",
        "option_b": "Les critères varient selon les provinces, ce qui complique les choses",
        "option_c": "Il n'y a pas de critères du tout",
        "option_d": "Les provinces n'existent plus",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quelle est la position de la personne sur les nouvelles mesures ?",
        "passage_or_audio_desc": "🔊 Transcription : « Je comprends l'inquiétude de certains, mais à mon sens, les nouvelles mesures vont plutôt simplifier les démarches à moyen terme. »",
        "option_a": "Elle pense qu'elles vont compliquer les choses",
        "option_b": "Elle pense qu'elles vont simplifier les démarches à moyen terme",
        "option_c": "Elle refuse de donner son avis",
        "option_d": "Elle pense qu'elles n'auront aucun effet",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "B2",
        "question_text": "Quel est, selon la personne, le principal obstacle rencontré par les nouveaux arrivants ?",
        "passage_or_audio_desc": "🔊 Transcription : « Entre nous, je pense que le principal obstacle n'est pas la langue, mais plutôt la méconnaissance des codes du marché du travail local. »",
        "option_a": "La langue",
        "option_b": "La méconnaissance des codes du marché du travail local",
        "option_c": "Le manque de diplômes",
        "option_d": "Le manque de motivation",
        "correct_option": "b",
    },
    # ===== Compréhension orale — niveau C1 (6) =====
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Que suggère la personne dans cet extrait ?",
        "passage_or_audio_desc": "🔊 Transcription : « On aurait tort de réduire cette problématique à une simple question de moyens financiers ; elle renvoie surtout à des enjeux structurels bien plus profonds. »",
        "option_a": "Le problème est uniquement financier",
        "option_b": "Le problème dépasse largement la question financière",
        "option_c": "Il n'y a aucun problème structurel",
        "option_d": "Les moyens financiers résolvent tout",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Quel équilibre la personne cherche-t-elle à exprimer ?",
        "passage_or_audio_desc": "🔊 Transcription : « Il ne s'agit pas tant de nier les progrès accomplis que de rappeler combien le chemin qu'il reste à parcourir demeure considérable. »",
        "option_a": "Nier tout progrès accompli",
        "option_b": "Reconnaître les progrès tout en soulignant le chemin restant",
        "option_c": "Affirmer que tout est déjà résolu",
        "option_d": "Refuser de parler du sujet",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Que reproche la personne aux chiffres avancés ?",
        "passage_or_audio_desc": "🔊 Transcription : « À l'évidence, les chiffres avancés méritent d'être nuancés, tant les méthodologies utilisées diffèrent sensiblement d'une étude à l'autre. »",
        "option_a": "Ils sont parfaitement fiables",
        "option_b": "Ils devraient être nuancés à cause de méthodologies différentes",
        "option_c": "Ils n'existent pas",
        "option_d": "Ils sont tous identiques",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Quel constat fait la personne malgré les efforts reconnus ?",
        "passage_or_audio_desc": "🔊 Transcription : « Loin de moi l'idée de minimiser les efforts consentis, mais force est de constater que les résultats tardent à se matérialiser sur le terrain. »",
        "option_a": "Les résultats sont déjà pleinement visibles",
        "option_b": "Les résultats tardent à apparaître concrètement",
        "option_c": "Il n'y a eu aucun effort",
        "option_d": "Le sujet est clos",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Quelle nuance la personne apporte-t-elle sur la flexibilité accrue ?",
        "passage_or_audio_desc": "🔊 Transcription : « On pourrait arguer que la flexibilité accrue profite à tous, mais dans les faits, elle semble surtout bénéficier à ceux qui maîtrisent déjà les rouages du système. »",
        "option_a": "La flexibilité profite également à tous sans exception",
        "option_b": "La flexibilité profite surtout à ceux qui connaissent déjà le système",
        "option_c": "La flexibilité ne profite à personne",
        "option_d": "Le système n'a pas de rouages",
        "correct_option": "b",
    },
    {
        "section": "comprehension_orale",
        "niveau": "C1",
        "question_text": "Quelle attitude la personne recommande-t-elle face à la réforme ?",
        "passage_or_audio_desc": "🔊 Transcription : « Il conviendrait de se garder de tout optimisme béat, tant les incertitudes entourant la mise en œuvre de cette réforme demeurent nombreuses. »",
        "option_a": "Un optimisme total et sans réserve",
        "option_b": "Une prudence face aux nombreuses incertitudes",
        "option_c": "Un rejet complet de la réforme",
        "option_d": "Une indifférence totale",
        "correct_option": "b",
    },
]

# --- Sujets d'expression écrite / orale (table tcf_expression_prompts) ---
# Un sujet aléatoire est tiré à chaque visite via GET /api/tcf/expression-prompts.
EXPRESSION_PROMPTS = [
    {
        "section": "expression_ecrite",
        "prompt_text": "Vous écrivez à un ami pour lui raconter votre installation dans une nouvelle ville au Canada. Décrivez vos premières impressions (150 mots minimum).",
    },
    {
        "section": "expression_ecrite",
        "prompt_text": "Vous répondez à une petite annonce pour un logement à louer. Présentez-vous et expliquez pourquoi vous seriez un(e) bon(ne) locataire (150 mots minimum).",
    },
    {
        "section": "expression_ecrite",
        "prompt_text": "Un ami vous demande des conseils pour préparer son entretien d'embauche au Canada. Rédigez-lui un message avec vos recommandations (150 mots minimum).",
    },
    {
        "section": "expression_ecrite",
        "prompt_text": "Vous écrivez un courriel à votre employeur pour demander un aménagement d'horaire afin de suivre des cours de français en soirée (150 mots minimum).",
    },
    {
        "section": "expression_ecrite",
        "prompt_text": "Rédigez un texte expliquant les défis et les avantages que vous associez à l'idée de vous installer dans une nouvelle province ou un nouveau pays (150 mots minimum).",
    },
    {
        "section": "expression_ecrite",
        "prompt_text": "Vous répondez à un forum en ligne pour donner votre avis sur l'importance d'apprendre le français avant d'immigrer au Canada (150 mots minimum).",
    },
    {
        "section": "expression_orale",
        "prompt_text": "Décrivez votre parcours professionnel et expliquez pourquoi vous souhaitez immigrer au Canada. Rédigez ici la transcription de ce que vous diriez à l'oral (1-2 minutes).",
    },
    {
        "section": "expression_orale",
        "prompt_text": "Présentez votre famille et expliquez comment vous envisagez votre vie quotidienne après votre installation au Canada. Rédigez la transcription de votre présentation orale (1-2 minutes).",
    },
    {
        "section": "expression_orale",
        "prompt_text": "Un(e) ami(e) vous demande de lui expliquer les démarches que vous avez entreprises pour préparer votre projet d'immigration. Rédigez la transcription de votre réponse orale (1-2 minutes).",
    },
    {
        "section": "expression_orale",
        "prompt_text": "Expliquez à l'oral pourquoi vous avez choisi telle ville ou province plutôt qu'une autre pour vous installer. Rédigez la transcription de votre réponse (1-2 minutes).",
    },
    {
        "section": "expression_orale",
        "prompt_text": "Décrivez une difficulté que vous avez rencontrée récemment et la façon dont vous l'avez résolue. Rédigez la transcription de votre réponse orale (1-2 minutes).",
    },
    {
        "section": "expression_orale",
        "prompt_text": "Présentez oralement vos objectifs professionnels pour les cinq prochaines années au Canada. Rédigez la transcription de cette présentation (1-2 minutes).",
    },
]


def seed_if_empty():
    with db_cursor(commit=True) as cur:
        cur.execute("SELECT COUNT(*) AS c FROM tcf_packs")
        if cur.fetchone()["c"] == 0:
            for p in PACKS:
                cur.execute(
                    """INSERT INTO tcf_packs
                    (name, description, price_mad, original_price_mad, is_popular,
                     duration_days, ai_correction_credits)
                    VALUES (?, ?, ?, ?, ?, ?, ?)""",
                    (p["name"], p["description"], p["price_mad"], p["original_price_mad"], p["is_popular"],
                     p["duration_days"], p["ai_correction_credits"]),
                )

        cur.execute("SELECT COUNT(*) AS c FROM tcf_questions")
        if cur.fetchone()["c"] == 0:
            for q in TCF_QUESTIONS + TCF_QUESTIONS_EXTRA:
                cur.execute(
                    """INSERT INTO tcf_questions
                    (section, niveau, question_text, passage_or_audio_desc,
                     option_a, option_b, option_c, option_d, correct_option)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (q["section"], q["niveau"], q["question_text"], q["passage_or_audio_desc"],
                     q["option_a"], q["option_b"], q["option_c"], q["option_d"], q["correct_option"]),
                )

        cur.execute("SELECT COUNT(*) AS c FROM tcf_expression_prompts")
        if cur.fetchone()["c"] == 0:
            for p in EXPRESSION_PROMPTS:
                cur.execute(
                    "INSERT INTO tcf_expression_prompts (section, prompt_text) VALUES (?, ?)",
                    (p["section"], p["prompt_text"]),
                )
